In [1]:
# importar biblioteca

In [2]:
import numpy as np

In [3]:
# array a partir de uma lista

In [5]:
qtde = [2,5,10,20,35]
custo = [100, 110, 120, 130, 140]

In [7]:
arr1 = np.array(qtde)

In [8]:
arr2 = np.array(custo)

In [9]:
estoque = arr1*arr2

In [11]:
estoque

array([ 200,  550, 1200, 2600, 4900])

In [27]:
valor = [100,200,300,400]
valor_revenda = [190,288,422,563]

In [28]:
arr6 = np.array(valor)

In [29]:
arr7 = np.array(valor_revenda)

In [30]:
lucro = arr7-arr6

In [32]:
lucro

array([ 90,  88, 122, 163])

In [33]:
# arrays a partir do numpy

In [34]:
#arange

In [36]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [40]:
np.arange(0,21,2,dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [41]:
#Linspace(): é usado para criar um array com numeros definidos de elementos

In [43]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [44]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
#Random - rand, randn, randint

In [48]:
np.random.rand(10)

array([0.02667782, 0.69435792, 0.40943646, 0.31325106, 0.90980291,
       0.99857184, 0.57249678, 0.89010356, 0.94031172, 0.96662048])

In [50]:
np.random.randn(10)

array([-0.51758799, -0.87202044, -0.92933819,  0.56572508, -0.89716316,
       -1.68948001,  0.54298385,  0.6394637 , -0.71117424,  0.40794346])

In [52]:
np.random.randint(10,100,30)

array([42, 94, 95, 50, 30, 58, 54, 18, 85, 52, 88, 92, 43, 22, 99, 23, 91,
       15, 85, 74, 48, 69, 46, 15, 40, 14, 44, 28, 20, 79])

In [53]:
#Zeros e Uns se tenho dois[] é um array bidimensional

In [54]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])