In [1]:
# criando array unidimensional

In [2]:
import numpy as np

In [5]:
arr = np.arange(1,11,dtype=int)

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# indexação de arrays unidimensionais

In [10]:
arr[4]

5

In [15]:
arr[2:5]

array([3, 4, 5])

In [18]:
arr[:5]

array([1, 2, 3, 4, 5])

In [20]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [21]:
# indexação de arrays bidimensionais

In [23]:
arr2 = np.random.randint(10,50,size=(4,4))

In [25]:
arr2

array([[45, 16, 46, 20],
       [34, 23, 13, 44],
       [45, 14, 38, 28],
       [22, 15, 10, 21]])

In [27]:
arr2[2][2]

38

In [30]:
arr2[3][2]

10

In [32]:
# primeiro conta [linha] de cima para baixo, depois [coluna] da esquerda para direita

In [34]:
arr2[3][3]

21

In [36]:
arr3 = np.random.randint(1,101,size=(10,10))

In [38]:
arr3

array([[84, 72, 44, 44, 90, 63, 93, 24, 63, 20],
       [65, 45, 13, 94, 88, 36, 68, 76, 96, 68],
       [59,  7,  8, 70, 67, 80, 29, 65, 60, 47],
       [67, 78, 91,  8, 33, 93, 40, 84, 10, 35],
       [84, 81, 48,  3, 59, 52, 88, 86,  5, 29],
       [48,  2, 15, 76, 62, 38, 58, 54, 26, 90],
       [89, 86, 76, 54, 88,  3, 12, 44, 97,  8],
       [86, 45, 70, 14, 48, 69, 70,  7, 44, 41],
       [99,  4, 67, 79, 98, 48, 26, 36, 90, 89],
       [79, 88, 28, 35, 52, 69, 76, 94, 28, 67]])

In [40]:
arr3[8][8]

90

In [42]:
arr3[2][6]

29

In [44]:
arr3[5][3]

76

In [45]:
# 24,63,20,76,96,68,65,60,47

In [48]:
arr3[:3, 7:]

array([[24, 63, 20],
       [76, 96, 68],
       [65, 60, 47]])

In [49]:
# 9 33 93 3 59 52 

In [50]:
# col 3 4 5
# 3 4

In [52]:
arr3[3:5,3:6]

array([[ 8, 33, 93],
       [ 3, 59, 52]])

In [54]:
arr3

array([[84, 72, 44, 44, 90, 63, 93, 24, 63, 20],
       [65, 45, 13, 94, 88, 36, 68, 76, 96, 68],
       [59,  7,  8, 70, 67, 80, 29, 65, 60, 47],
       [67, 78, 91,  8, 33, 93, 40, 84, 10, 35],
       [84, 81, 48,  3, 59, 52, 88, 86,  5, 29],
       [48,  2, 15, 76, 62, 38, 58, 54, 26, 90],
       [89, 86, 76, 54, 88,  3, 12, 44, 97,  8],
       [86, 45, 70, 14, 48, 69, 70,  7, 44, 41],
       [99,  4, 67, 79, 98, 48, 26, 36, 90, 89],
       [79, 88, 28, 35, 52, 69, 76, 94, 28, 67]])

In [56]:
arr3[[3,5,7]]

array([[67, 78, 91,  8, 33, 93, 40, 84, 10, 35],
       [48,  2, 15, 76, 62, 38, 58, 54, 26, 90],
       [86, 45, 70, 14, 48, 69, 70,  7, 44, 41]])