In [1]:
# Seleção de arrays no numpy

In [2]:
import numpy as np

In [3]:
a = 40
b = 70

In [6]:
a>b

False

In [8]:
cadastro = np.random.randint(15,51,size=(15,15))

In [10]:
cadastro

array([[30, 36, 20, 32, 41, 16, 26, 48, 32, 39, 29, 45, 33, 20, 36],
       [27, 48, 23, 35, 26, 15, 25, 33, 21, 47, 17, 33, 24, 40, 15],
       [39, 35, 44, 19, 49, 24, 28, 32, 37, 38, 19, 19, 49, 25, 23],
       [21, 15, 36, 17, 27, 29, 21, 22, 16, 46, 46, 27, 35, 33, 15],
       [15, 31, 17, 35, 30, 21, 32, 19, 46, 25, 48, 47, 49, 42, 23],
       [41, 40, 37, 25, 22, 46, 37, 39, 43, 18, 41, 43, 29, 48, 22],
       [25, 39, 33, 23, 34, 50, 16, 29, 41, 18, 33, 35, 40, 42, 18],
       [36, 40, 36, 37, 20, 16, 49, 37, 44, 33, 24, 49, 27, 47, 34],
       [21, 32, 16, 30, 40, 50, 47, 28, 42, 44, 37, 47, 23, 39, 49],
       [49, 38, 48, 30, 50, 31, 21, 23, 26, 46, 49, 24, 43, 15, 34],
       [22, 35, 50, 32, 34, 24, 49, 29, 26, 27, 39, 47, 15, 38, 16],
       [25, 19, 41, 46, 26, 16, 44, 26, 26, 46, 26, 19, 24, 15, 35],
       [48, 20, 26, 15, 36, 38, 27, 43, 50, 15, 48, 34, 15, 17, 36],
       [21, 19, 43, 16, 22, 25, 20, 32, 34, 36, 49, 30, 38, 30, 50],
       [47, 21, 21, 50, 28, 31, 21

In [11]:
cadastro_maior18 = cadastro > 18

In [12]:
cadastro_maior18

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True, False,  True, False,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True, False],
       [False,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True, Fa

In [14]:
cadastro[cadastro_maior18]

array([30, 36, 20, 32, 41, 26, 48, 32, 39, 29, 45, 33, 20, 36, 27, 48, 23,
       35, 26, 25, 33, 21, 47, 33, 24, 40, 39, 35, 44, 19, 49, 24, 28, 32,
       37, 38, 19, 19, 49, 25, 23, 21, 36, 27, 29, 21, 22, 46, 46, 27, 35,
       33, 31, 35, 30, 21, 32, 19, 46, 25, 48, 47, 49, 42, 23, 41, 40, 37,
       25, 22, 46, 37, 39, 43, 41, 43, 29, 48, 22, 25, 39, 33, 23, 34, 50,
       29, 41, 33, 35, 40, 42, 36, 40, 36, 37, 20, 49, 37, 44, 33, 24, 49,
       27, 47, 34, 21, 32, 30, 40, 50, 47, 28, 42, 44, 37, 47, 23, 39, 49,
       49, 38, 48, 30, 50, 31, 21, 23, 26, 46, 49, 24, 43, 34, 22, 35, 50,
       32, 34, 24, 49, 29, 26, 27, 39, 47, 38, 25, 19, 41, 46, 26, 44, 26,
       26, 46, 26, 19, 24, 35, 48, 20, 26, 36, 38, 27, 43, 50, 48, 34, 36,
       21, 19, 43, 22, 25, 20, 32, 34, 36, 49, 30, 38, 30, 50, 47, 21, 21,
       50, 28, 31, 21, 29, 37, 21, 24, 37, 25, 47, 21])

In [16]:
arr = cadastro[cadastro>8]

array([30, 36, 20, 32, 41, 16, 26, 48, 32, 39, 29, 45, 33, 20, 36, 27, 48,
       23, 35, 26, 15, 25, 33, 21, 47, 17, 33, 24, 40, 15, 39, 35, 44, 19,
       49, 24, 28, 32, 37, 38, 19, 19, 49, 25, 23, 21, 15, 36, 17, 27, 29,
       21, 22, 16, 46, 46, 27, 35, 33, 15, 15, 31, 17, 35, 30, 21, 32, 19,
       46, 25, 48, 47, 49, 42, 23, 41, 40, 37, 25, 22, 46, 37, 39, 43, 18,
       41, 43, 29, 48, 22, 25, 39, 33, 23, 34, 50, 16, 29, 41, 18, 33, 35,
       40, 42, 18, 36, 40, 36, 37, 20, 16, 49, 37, 44, 33, 24, 49, 27, 47,
       34, 21, 32, 16, 30, 40, 50, 47, 28, 42, 44, 37, 47, 23, 39, 49, 49,
       38, 48, 30, 50, 31, 21, 23, 26, 46, 49, 24, 43, 15, 34, 22, 35, 50,
       32, 34, 24, 49, 29, 26, 27, 39, 47, 15, 38, 16, 25, 19, 41, 46, 26,
       16, 44, 26, 26, 46, 26, 19, 24, 15, 35, 48, 20, 26, 15, 36, 38, 27,
       43, 50, 15, 48, 34, 15, 17, 36, 21, 19, 43, 16, 22, 25, 20, 32, 34,
       36, 49, 30, 38, 30, 50, 47, 21, 21, 50, 28, 31, 21, 29, 37, 21, 24,
       37, 25, 47, 21])

In [18]:
arr = cadastro[cadastro>8]

In [20]:
len(arr)

225

In [22]:
cadastro_maior18

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True, False,  True, False,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True, False],
       [False,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True, Fa

In [24]:
cadastro[cadastro>30]

array([36, 32, 41, 48, 32, 39, 45, 33, 36, 48, 35, 33, 47, 33, 40, 39, 35,
       44, 49, 32, 37, 38, 49, 36, 46, 46, 35, 33, 31, 35, 32, 46, 48, 47,
       49, 42, 41, 40, 37, 46, 37, 39, 43, 41, 43, 48, 39, 33, 34, 50, 41,
       33, 35, 40, 42, 36, 40, 36, 37, 49, 37, 44, 33, 49, 47, 34, 32, 40,
       50, 47, 42, 44, 37, 47, 39, 49, 49, 38, 48, 50, 31, 46, 49, 43, 34,
       35, 50, 32, 34, 49, 39, 47, 38, 41, 46, 44, 46, 35, 48, 36, 38, 43,
       50, 48, 34, 36, 43, 32, 34, 36, 49, 38, 50, 47, 50, 31, 37, 37, 47])

In [25]:
arr4 = cadastro[cadastro>30]

In [27]:
len(arr4)

119

In [28]:
condicao = (cadastro>30)

In [30]:
extraido = np.extract(condicao, cadastro)

In [31]:
extraido

array([36, 32, 41, 48, 32, 39, 45, 33, 36, 48, 35, 33, 47, 33, 40, 39, 35,
       44, 49, 32, 37, 38, 49, 36, 46, 46, 35, 33, 31, 35, 32, 46, 48, 47,
       49, 42, 41, 40, 37, 46, 37, 39, 43, 41, 43, 48, 39, 33, 34, 50, 41,
       33, 35, 40, 42, 36, 40, 36, 37, 49, 37, 44, 33, 49, 47, 34, 32, 40,
       50, 47, 42, 44, 37, 47, 39, 49, 49, 38, 48, 50, 31, 46, 49, 43, 34,
       35, 50, 32, 34, 49, 39, 47, 38, 41, 46, 44, 46, 35, 48, 36, 38, 43,
       50, 48, 34, 36, 43, 32, 34, 36, 49, 38, 50, 47, 50, 31, 37, 37, 47])